-- 8. 
-- (i) Prove that if X is a countably infinite set, and Y ⊆ X is an infinite subset, then Y is countably infinite. 
--(ii) Are there countably many irrational numbers? Countably many complex numbers? WhataboutQ(i)={a+bi : a,b∈Q}?