import algebra.order data.fintype

-- sheet 6

-- 1. Let G be a group. For each of the following statements, say whether or not it is true in general, and give a proof or a counterexample.

-- -- (a) If G is not cyclic then G is not abelian.
-- theorem sheet06_q1a:
-- -- (b) For every element g of G there is an abelian subgroup of G which contains g.
-- theorem sheet06_q1b:
-- -- (c) If G = ⟨g⟩ is an infinite cyclic group, then the only generators for G are g
-- -- and g−1.
-- theorem sheet06_q1c:
-- -- (d) If G is infinite then G has an element of infinite order.
-- theorem sheet06_q1d:
-- -- (e) If the order of every non-identity element of G is a prime number, then G is cyclic.
-- theorem sheet06_q1e:
-- (f) If G has order 4, then G is abelian.
--theorem sheet06_q1f:
-- -- (g) If G is abelian then every subgroup of G is abelian.
-- theorem sheet06_q1g:
-- -- (h) If G is cyclic then every subgroup of G is cyclic.
-- theorem sheet06_q1h:
-- -- (i) If x, y ∈ G, then x and y−1xy have the same order.
-- theorem sheet06_q1i:
-- (j) If x,y ∈ G have order 2, then xy has order 2.
--theorem sheet06_q1j:

-- -- *2. (a) Write down all of the cycle shapes of the elements of S5. For each cycle shape, calculate how many elements there are with that shape. (Check that your answers add up to |S5| = 120.)
-- theorem sheet06_q2a:
-- -- (b) How many elements of S5 have order 2?
-- theorem sheet06_q2b:
-- -- (c) How many subgroups of size 3 are there in the group S5?
-- theorem sheet06_q2c:
-- -- 3. (a) Let H1 be the cyclic subgroup ⟨(1234)⟩ of S4. Write down the right cosets of H in S4.
-- theorem sheet06_q2d:
-- -- (b) Find a subgroup H2 of S4 of order 4, in which all of the non-identity elements have the same cycle shape. Write down its right cosets in S4.
-- theorem sheet06_q2e:
-- -- (c) Which of the right cosets you have found for H1 and H2 are also left cosets?
-- theorem sheet06_q2f:

-- 4. Let G be a finite group of order n, and H a subgroup of G of order m.

-- -- (a) Forx,y∈G,showthatHx=Hy⇐⇒xy−1 ∈H.
-- theorem sheet06_q4a (x y : G) : x * l  = x * l ↔ x * y⁻¹ ∈ H := sorry 
-- -- (b) Suppose that r = n/m. Let x ∈ G. Show that there is an integer k in the range 1≤k≤r,suchthatxk ∈H.
-- theorem sheet06_q4b:
-- -- (c) Give an example to show that in (b), the integer k need not divide r.
-- theorem sheet06_q4c:
-- -- 5. Let G be a group,and let S be a subset of G.We say that S generates G if every element in G can be written as a product of elements of S and their inverses. (For example, if G is the cyclic group ⟨g⟩, then {g} generates G.)
-- theorem sheet06_q4d:
-- -- (a) Let 2≤k≤n. Show that a k-cycle(a1 ...,ak)in S n can be written as a product of k−1 distinct cycles of length 2. Deduce that the set of 2-cycles in Sn generates Sn.
-- theorem sheet06_q4e:
-- -- (b) Show that the group (Q, +) is not generated by any finite subset.
-- theorem sheet06_q4f:
