import algebra.order data.fintype group_theory.subgroup data.set.basic data.rat

variables {G : Type*} [group G]
variables (H K : set G)
variables [is_subgroup H] [is_subgroup K]

definition is_cyclic (G : Type*) [group G] := ∃ x : G, gpowers x = set.univ
-- 1. Let G be a group. For each of the following statements, say whether or not it is true in general, and give a proof or a counterexample.

-- (a) If G is not cyclic then G is not abelian.
    -- False (e.g : (ℝ,+))

-- (b) For every element g of G there is an abelian subgroup of G which contains g.
--theorem sheet06_q1b (G : Type*) (g : G) (H : Type*) [comm_group H]: ∃ H ∧ g ∈ H := sorry
--theorem sheet06_q1b (G : Type*) : exists H : set G, [is_subgroup H] ∧ (∀ a b ∈ H, a * b = b * a) := sorry 


-- (c) If G = ⟨g⟩ is an infinite cyclic group, then the only generators for G are g and g⁻¹.
--theorem sheet06_q1c (G : Type*) : is_cyclic G → (gpowers g = G) ∧ (gpowers g⁻¹ = G) := sorry 

-- (d) If G is infinite then G has an element of infinite order.
    -- False (e.g: set of all complex roots of unity)

-- (e) If the order of every non-identity element of G is a prime number, then G is cyclic.
--theorem sheet06_q1e (G : Type*) (g : G) (g ≠ 1) (order_of g : prime) : is_cyclic G := sorry

-- (f) If G has order 4, then G is abelian.
    --False. (e.g: Klein Four Group)

-- (g) If G is abelian then every subgroup of G is abelian.
--theorem sheet06_q1g (G : Type*) [comm_group G] (H : set G) [is_subgroup H] : comm_group H := sorry  

-- (h) If G is cyclic then every subgroup of G is cyclic.
--theorem sheet06_q1h (G : Type*) : is_cyclic G → is_cyclic H := sorry

-- (i) If x, y ∈ G, then x and y⁻¹xy have the same order.
-- theorem sheet06_q1i (G : Type*) (x y : G): order_of x = order_of (y⁻¹ * x * y) := sorry

-- (j) If x,y ∈ G have order 2, then xy has order 2.
    -- False. (e.g:(1,2),(2,3)∈ S₃)

definition gsymmetric (n : ℕ) := equiv.perm (fin n)

-- *2. (a) Write down all of the cycle shapes of the elements of S₅. For each cycle shape, calculate how many elements there are with that shape. (Check that your answers add up to |S₅| = 120.)
-- theorem sheet06_q2a:

-- (b) How many elements of S₅ have order 2?
-- theorem sheet06_q2b:

-- (c) How many subgroups of size 3 are there in the group S₅?
-- theorem sheet06_q2c:

-- 3. (a) Let H₁ be the cyclic subgroup ⟨(1234)⟩ of S₄ . Write down the right cosets of H in S₄.
-- theorem sheet06_q2d:

-- (b) Find a subgroup H₂ of S₄ of order 4, in which all of the non-identity elements have the same cycle shape. Write down its right cosets in S₄.
-- theorem sheet06_q2e:

-- (c) Which of the right cosets you have found for H₁ and H₂ are also left cosets?
-- theorem sheet06_q2f:

-- 4. Let G be a finite group of order n, and H a subgroup of G of order m.

-- (a) For x,y ∈ G, show that Hx = Hy ⇐⇒ xy⁻¹ ∈ H.
-- theorem sheet06_q4a (x y : G) : x * l  = x * l ↔ x * y⁻¹ ∈ H := sorry 

-- (c) Give an example to show that in (b), the integer k need not divide r.
-- theorem sheet06_q4c:

-- 5. Let G be a group,and let S be a subset of G.We say that S generates G if every element in G can be written as a product of elements of S and their inverses. (For example, if G is the cyclic group ⟨g⟩, then {g} generates G.)
-- theorem sheet06_q4d:

-- (a) Let 2≤k≤n. Show that a k-cycle (a1 ...,ak)in Sn can be written as a product of k−1 distinct cycles of length 2. Deduce that the set of 2-cycles in Sn generates Sn.
-- theorem sheet06_q4e:

-- (b) Show that the group (Q, +) is not generated by any finite subset.
--theorem sheet06_q4f (:

-- bit0 stands for the binary representation of 2*n. n in binary -> 2*n appends a zero
#print bit0