import linear_algebra
-- 1.
-- (ii) Let V be the vector space of all 2×2 matrices over R. Which of the following functions T : V −→ V are linear transformations?
-- (a) T(A)=A2 ∀A∈V􏰃
-- (b) T(A)= −1 1 A ∀ A∈V
-- Find a linear transformation T : R2 −→ R3 which sends (1,0) to (1,1,0) and (1, 1) to (1, 0, −1).
-- (i) Which of the following functions T : R3 −→ R2 are linear transformations? (a) T(x1,x2,x3)=(x1 +x2 −x3,2x1 +x2)
-- (b) T (x1, x2, x3) = (0,
-- (c) T(x1,x2,x3)=(x1x2,x3)
-- (iii) (a)
-- (b) Find two different linear transformations R3 −→ R2 which send (1, 1, 0) to (1, 1)
-- *2.
-- and (0, 1, 1) to (0, 1).
-- (i) Give an example of a linear transformation T : R2 −→ R3 such that T(v) = (1,0,0) for exactly one vector v ∈ R2.
-- (ii) Give an example of a linear transformation T : R2 −→ R3 such that T(v) = (1,0,0) for no vector v ∈ R2.
-- (iii) Give an example of a linear transformation T : R2 −→ R3 such that T(v) = (1,0,0) for infinitely many vectors v ∈ R2.
-- (iv) Show that there is no linear transformation T : R2 −→ R3 such that T (v) = (1, 0, 0) for exactly two vectors v ∈ R2.
-- 3.
-- (ii) Let V be the vector space of polynomials of degree at most 2 over R. Define T : V −→ V by
-- T(ax2 +bx+c)=(a+b+c)x2 +(c−a)x+(a+3b+5c). Find bases of Ker(T) and Im(T).
-- (i) Define T : R3 −→ R3 by T(x1,x2,x3) = (x1 − x2,x2 − x3,x3 − x1). Find bases of Ker(T) and Im(T). For which values of k is the vector (1,3,k) in Ker(T) or Im(T)?
-- (iii) Let V be as in part (ii), and define S : V −→ V by
-- S(p(x)) = p(1 + x) − p(x) for p(x) ∈ V.
-- (So for example, S(x2) = (x+1)2−x2 = 2x+1.) Show that S is a linear transformation, and find bases of Ker(S) and Im(S).
-- 4.
-- (b) Prove that T is surjective if and only if Ker(T ) = {0}.
-- (ii) Find an example of a linear transformation T : R2 −→ R2 such that Ker(T ) = Im(T ).
-- (iii) Prove that there does not exist a linear transformation T : R3 −→ R3 such that Ker(T ) = Im(T ).